export interface User {
  image: string;
  firstName: string;
  lastName: string;
  country: string;
  rank: number;
}

export const data: User[] = [
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/2.jpg',
    firstName: 'Leon',
    lastName: 'Wells',
    country: 'United Kingdom',
    rank: 0,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/99.jpg',
    firstName: 'Sydney',
    lastName: 'Kraai',
    country: 'Netherlands',
    rank: 1,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/60.jpg',
    firstName: 'Martin',
    lastName: 'Mitchell',
    country: 'Australia',
    rank: 2,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/43.jpg',
    firstName: 'Silke',
    lastName: 'Rasmussen',
    country: 'Denmark',
    rank: 3,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/50.jpg',
    firstName: 'Ramon',
    lastName: 'Thompson',
    country: 'United Kingdom',
    rank: 4,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/83.jpg',
    firstName: 'Manuela',
    lastName: 'Marquez',
    country: 'Spain',
    rank: 5,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/34.jpg',
    firstName: 'Brielle',
    lastName: 'Jean-Baptiste',
    country: 'Canada',
    rank: 6,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/74.jpg',
    firstName: 'Virgil',
    lastName: 'Marshall',
    country: 'United States',
    rank: 7,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/34.jpg',
    firstName: 'Michelle',
    lastName: 'Chapman',
    country: 'Ireland',
    rank: 8,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/97.jpg',
    firstName: 'Ray',
    lastName: 'Miller',
    country: 'Australia',
    rank: 9,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/81.jpg',
    firstName: 'Cameron',
    lastName: 'Moore',
    country: 'Ireland',
    rank: 10,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/63.jpg',
    firstName: 'Annedore',
    lastName: 'Eichmann',
    country: 'Germany',
    rank: 11,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/47.jpg',
    firstName: 'Andrea',
    lastName: 'Vargas',
    country: 'Spain',
    rank: 12,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/85.jpg',
    firstName: 'Kai',
    lastName: 'Blanchard',
    country: 'Switzerland',
    rank: 13,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/1.jpg',
    firstName: 'Andre',
    lastName: 'Cox',
    country: 'Ireland',
    rank: 14,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/13.jpg',
    firstName: 'Andrea',
    lastName: 'Kelly',
    country: 'Australia',
    rank: 15,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/85.jpg',
    firstName: 'Lenni',
    lastName: 'Toro',
    country: 'Finland',
    rank: 16,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/34.jpg',
    firstName: 'Brooke',
    lastName: 'Hall',
    country: 'New Zealand',
    rank: 17,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/49.jpg',
    firstName: 'Harvey',
    lastName: 'Hart',
    country: 'Ireland',
    rank: 18,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/82.jpg',
    firstName: 'Natalia',
    lastName: 'Esteban',
    country: 'Spain',
    rank: 19,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/84.jpg',
    firstName: 'Adália',
    lastName: 'Nascimento',
    country: 'Brazil',
    rank: 20,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/89.jpg',
    firstName: 'Jacob',
    lastName: 'Rodriguez',
    country: 'United States',
    rank: 21,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/14.jpg',
    firstName: 'Caroline',
    lastName: 'Cunningham',
    country: 'Ireland',
    rank: 22,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/59.jpg',
    firstName: 'Aubree',
    lastName: 'Hernandez',
    country: 'United States',
    rank: 23,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/95.jpg',
    firstName: 'Monica',
    lastName: 'Esteban',
    country: 'Spain',
    rank: 24,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/44.jpg',
    firstName: 'Jocelino',
    lastName: 'Campos',
    country: 'Brazil',
    rank: 25,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/36.jpg',
    firstName: 'Theo',
    lastName: 'Lo',
    country: 'Canada',
    rank: 26,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/18.jpg',
    firstName: 'Eemeli',
    lastName: 'Mikkola',
    country: 'Finland',
    rank: 27,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/56.jpg',
    firstName: 'Alexis',
    lastName: 'Mitchell',
    country: 'Canada',
    rank: 28,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/19.jpg',
    firstName: 'رونیکا',
    lastName: 'پارسا',
    country: 'Iran',
    rank: 29,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/82.jpg',
    firstName: 'Eren',
    lastName: 'Paksüt',
    country: 'Turkey',
    rank: 30,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/86.jpg',
    firstName: 'Rafael',
    lastName: 'Rubio',
    country: 'Spain',
    rank: 31,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/66.jpg',
    firstName: 'Minea',
    lastName: 'Keranen',
    country: 'Finland',
    rank: 32,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/53.jpg',
    firstName: 'Henry',
    lastName: 'Austin',
    country: 'United States',
    rank: 33,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/23.jpg',
    firstName: 'Fernando',
    lastName: 'Wells',
    country: 'United States',
    rank: 34,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/5.jpg',
    firstName: 'Miro',
    lastName: 'Korpi',
    country: 'Finland',
    rank: 35,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/83.jpg',
    firstName: 'Abigail',
    lastName: 'Craig',
    country: 'Ireland',
    rank: 36,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/53.jpg',
    firstName: 'Fernando',
    lastName: 'Andrews',
    country: 'United States',
    rank: 37,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/89.jpg',
    firstName: 'Giray',
    lastName: 'Sarıoğlu',
    country: 'Turkey',
    rank: 38,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/84.jpg',
    firstName: 'Fiona',
    lastName: 'Lilleås',
    country: 'Norway',
    rank: 39,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/88.jpg',
    firstName: 'Wallace',
    lastName: 'Castillo',
    country: 'United States',
    rank: 40,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/73.jpg',
    firstName: 'مرسانا',
    lastName: 'صدر',
    country: 'Iran',
    rank: 41,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/25.jpg',
    firstName: 'مهراد',
    lastName: 'نجاتی',
    country: 'Iran',
    rank: 42,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/4.jpg',
    firstName: 'Cléia',
    lastName: 'Ramos',
    country: 'Brazil',
    rank: 43,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/45.jpg',
    firstName: 'Joaquin',
    lastName: 'Moerkerken',
    country: 'Netherlands',
    rank: 44,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/24.jpg',
    firstName: 'Ömür',
    lastName: 'Tuğluk',
    country: 'Turkey',
    rank: 45,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/8.jpg',
    firstName: 'Vanessa',
    lastName: 'Kalisch',
    country: 'Germany',
    rank: 46,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/63.jpg',
    firstName: 'Sara',
    lastName: 'Caballero',
    country: 'Spain',
    rank: 47,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/14.jpg',
    firstName: 'نازنین',
    lastName: 'رضاییان',
    country: 'Iran',
    rank: 48,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/8.jpg',
    firstName: 'پرهام',
    lastName: 'سلطانی نژاد',
    country: 'Iran',
    rank: 49,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/60.jpg',
    firstName: 'Alison',
    lastName: 'Ray',
    country: 'United Kingdom',
    rank: 50,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/78.jpg',
    firstName: 'Fabien',
    lastName: 'Moreau',
    country: 'France',
    rank: 51,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/72.jpg',
    firstName: 'Colleen',
    lastName: 'Moreno',
    country: 'Australia',
    rank: 52,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/17.jpg',
    firstName: 'Randa',
    lastName: 'Vries',
    country: 'Netherlands',
    rank: 53,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/29.jpg',
    firstName: 'Vilho',
    lastName: 'Waisanen',
    country: 'Finland',
    rank: 54,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/89.jpg',
    firstName: 'Giray',
    lastName: 'Karaböcek',
    country: 'Turkey',
    rank: 55,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/6.jpg',
    firstName: 'Angie',
    lastName: 'Banks',
    country: 'Ireland',
    rank: 56,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/20.jpg',
    firstName: 'Julia',
    lastName: 'Marchand',
    country: 'Switzerland',
    rank: 57,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/80.jpg',
    firstName: 'Anton',
    lastName: 'Andersen',
    country: 'Denmark',
    rank: 58,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/34.jpg',
    firstName: 'Ashley',
    lastName: 'Ellis',
    country: 'United Kingdom',
    rank: 59,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/65.jpg',
    firstName: 'Linnea',
    lastName: 'Laine',
    country: 'Finland',
    rank: 60,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/42.jpg',
    firstName: 'Hugo',
    lastName: 'Ruiz',
    country: 'Spain',
    rank: 61,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/3.jpg',
    firstName: 'Ayşe',
    lastName: 'Nalbantoğlu',
    country: 'Turkey',
    rank: 62,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/0.jpg',
    firstName: 'Ivo',
    lastName: 'Lauritsen',
    country: 'Norway',
    rank: 63,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/43.jpg',
    firstName: 'Jaap',
    lastName: 'Numan',
    country: 'Netherlands',
    rank: 64,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/10.jpg',
    firstName: 'Lina',
    lastName: 'Vidal',
    country: 'Switzerland',
    rank: 65,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/59.jpg',
    firstName: 'Martin',
    lastName: 'Fuller',
    country: 'Australia',
    rank: 66,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/32.jpg',
    firstName: 'Warren',
    lastName: 'Brooks',
    country: 'Ireland',
    rank: 67,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/27.jpg',
    firstName: 'Jesse',
    lastName: 'Maijala',
    country: 'Finland',
    rank: 68,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/50.jpg',
    firstName: 'Mestan',
    lastName: 'Adıvar',
    country: 'Turkey',
    rank: 69,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/20.jpg',
    firstName: 'Maeva',
    lastName: 'Bouchard',
    country: 'Canada',
    rank: 70,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/80.jpg',
    firstName: 'Mia',
    lastName: 'Harris',
    country: 'United Kingdom',
    rank: 71,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/46.jpg',
    firstName: 'Marguerite',
    lastName: 'Barbier',
    country: 'Switzerland',
    rank: 72,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/3.jpg',
    firstName: 'Armand',
    lastName: 'Lopez',
    country: 'Switzerland',
    rank: 73,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/80.jpg',
    firstName: 'Dietmar',
    lastName: 'Heinemann',
    country: 'Germany',
    rank: 74,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/21.jpg',
    firstName: 'Manon',
    lastName: 'Lemaire',
    country: 'Switzerland',
    rank: 75,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/14.jpg',
    firstName: 'اميرمحمد',
    lastName: 'رضایی',
    country: 'Iran',
    rank: 76,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/7.jpg',
    firstName: 'Anton',
    lastName: 'Madsen',
    country: 'Denmark',
    rank: 77,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/42.jpg',
    firstName: 'Eivind',
    lastName: 'Sørland',
    country: 'Norway',
    rank: 78,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/82.jpg',
    firstName: 'بنیامین',
    lastName: 'جعفری',
    country: 'Iran',
    rank: 79,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/85.jpg',
    firstName: 'Slavica',
    lastName: 'Großer',
    country: 'Germany',
    rank: 80,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    firstName: 'Sário',
    lastName: 'Moura',
    country: 'Brazil',
    rank: 81,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/72.jpg',
    firstName: 'Younes',
    lastName: 'Smedsrud',
    country: 'Norway',
    rank: 82,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/9.jpg',
    firstName: 'Austin',
    lastName: 'Lee',
    country: 'New Zealand',
    rank: 83,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/30.jpg',
    firstName: 'Léandre',
    lastName: 'Vincent',
    country: 'France',
    rank: 84,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/52.jpg',
    firstName: 'Jenny',
    lastName: 'Van den Einden',
    country: 'Netherlands',
    rank: 85,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/5.jpg',
    firstName: 'Simon',
    lastName: 'Bouchard',
    country: 'Canada',
    rank: 86,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/47.jpg',
    firstName: 'Aldónio',
    lastName: 'Fernandes',
    country: 'Brazil',
    rank: 87,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/11.jpg',
    firstName: 'Tilde',
    lastName: 'Hansen',
    country: 'Denmark',
    rank: 88,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/23.jpg',
    firstName: 'Florence',
    lastName: 'Robinson',
    country: 'New Zealand',
    rank: 89,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/34.jpg',
    firstName: 'Annamarie',
    lastName: 'Renard',
    country: 'Switzerland',
    rank: 90,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
    firstName: 'Jadir',
    lastName: 'Souza',
    country: 'Brazil',
    rank: 91,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/26.jpg',
    firstName: 'آنیتا',
    lastName: 'رضایی',
    country: 'Iran',
    rank: 92,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/50.jpg',
    firstName: 'Leanne',
    lastName: 'Lévesque',
    country: 'Canada',
    rank: 93,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/30.jpg',
    firstName: 'Jayden',
    lastName: 'Davies',
    country: 'New Zealand',
    rank: 94,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/34.jpg',
    firstName: 'Mary',
    lastName: 'Silva',
    country: 'United States',
    rank: 95,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/24.jpg',
    firstName: 'Travis',
    lastName: 'Lopez',
    country: 'United Kingdom',
    rank: 96,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/7.jpg',
    firstName: 'Victoria',
    lastName: 'Larson',
    country: 'United Kingdom',
    rank: 97,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/men/33.jpg',
    firstName: 'Muharrem',
    lastName: 'Grosser',
    country: 'Germany',
    rank: 98,
  },
  {
    image: 'https://randomuser.me/api/portraits/thumb/women/14.jpg',
    firstName: 'Lillie',
    lastName: 'Fowler',
    country: 'United States',
    rank: 99,
  },
];
